name: Triggers
run-name: Estoy ejecutando triggers
on:
   pull_request: 
     types: [opened]
     paths:
       - '**.js'
   issues:
     types:
       - labeled
   workflow_dispatch:
      inputs:
        comida_favorita:
          description: 'Comida Favorita'
          default: Pizza
          required: true
          type: choice
          options:
            - Pizza
            - Hamburguesa
            - Hotdog
        trabajo:
          description: 'En qué trabajas'
          required: true
          type: string
   schedule: 
    - cron: '10 * * * *'
jobs:
  jobs-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir Comida
        run: echo "FOOD=${{ inputs.comida_favorita }}" >> $GITHUB_ENV
      - name: Tu trabajo
        run: echo "JOB=${{ inputs.trabajo }}" >> $GITHUB_ENV
      - name: Hola Mundo
        run: node index.js
    
  
        
          

    
